name: tnshealth
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  intl_phone_field: ^2.1.0
  image_picker: ^0.8.4+4
  flutter_speed_dial: ^5.0.0+1
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_core: ^1.12.0
  animated_splash_screen: ^1.2.0
  firebase_storage: ^10.2.16
  path_provider: ^2.0.10
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  


flutter:


  uses-material-design: true


  assets:
    - images/
   